defmodule Goodmao2Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :goodmao2

  # The session is stored in the cookie, signed *and encrypted*. Signing alone left it readable
  # by anyone holding the cookie, and during forced 2FA enrollment it carries the raw TOTP seed
  # (`:pending_2fa_setup_secret`). Changing either salt invalidates every session cookie once;
  # "remember me" users are signed back in from their separate cookie.
  # `secure: true` in prod stamps the Secure attribute so the session cookie never travels over
  # plain HTTP (defense-in-depth behind `force_ssl`). Dev serves both http://…:4000 and
  # https://…:4001, so the flag is off outside prod to keep the http dev origin usable.
  @session_options [
    store: :cookie,
    key: "_goodmao2_key",
    signing_salt: "CfBgOD5J",
    encryption_salt: "bz7KCf18",
    same_site: "Lax",
    secure: Mix.env() == :prod
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :goodmao2,
    gzip: not code_reloading?,
    only: Goodmao2Web.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :goodmao2
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # Magic-link, email-confirmation, and share links carry a live bearer token in the URL path,
  # and the request line Phoenix logs is the raw path — so those requests log at :debug, below
  # production's :info, rather than writing the tokens into the log. (Params are separately
  # scrubbed by `:filter_parameters`; nginx redacts its own access log.)
  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {__MODULE__, :request_log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Browser feature tests run the endpoint for real, so their requests arrive on the server's
  # own processes rather than the test's. This plug reads the sandbox owner out of the user
  # agent Wallaby stamps, letting those requests join the test's transaction -- without it a
  # browser test sees an empty database. Compiled only when :sql_sandbox is set, which is
  # config/test.exs alone.
  if Application.compile_env(:goodmao2, :sql_sandbox, false) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  plug Goodmao2Web.Router

  @doc false
  def request_log_level(%Plug.Conn{path_info: path_info}),
    do: if(token_in_path?(path_info), do: :debug, else: :info)

  defp token_in_path?(["users", "log-in", _token]), do: true
  defp token_in_path?(["users", "settings", "confirm-email", _token]), do: true
  defp token_in_path?(["entries", "shared", _token | _]), do: true
  defp token_in_path?(["reports", "shared", _token | _]), do: true
  defp token_in_path?(_path_info), do: false
end
