---
all:
  children:
    production:
      hosts:
        goodmao.tw:
          ansible_user: root
        # Replace with your server's IP or hostname
        # goodmao.example.com:
        #   ansible_user: root
