import Config

# Configure your database
config :goodmao2, Goodmao2.Repo,
  username: "goodmao2",
  password: "goodmao2",
  hostname: "localhost",
  database: "goodmao2_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :goodmao2, Goodmao2Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  # HTTPS in dev on :4001 with a self-signed certificate. Generate the cert once
  # (it is gitignored — per-machine, regenerable) with:
  #
  #     mix phx.gen.cert
  #
  # then browse https://localhost:4001 (accept the self-signed warning). The plain
  # HTTP server on :4000 keeps running too.
  https: [
    ip: {127, 0, 0, 1},
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "chqI8r0CgMrPISPxQGChgXDMf97VHOf19te5LD04wmQBuy5fMzl6BlNViD/wvWWG",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:goodmao2, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:goodmao2, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :goodmao2, Goodmao2Web.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/goodmao2_web/router\.ex$"E,
      ~r"lib/goodmao2_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :goodmao2, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# LifeLog media stored under a git-ignored dir at the project root (outside priv/static).
config :goodmao2, Goodmao2.Media, storage_dir: Path.expand("../media", __DIR__)

# WebAuthn/FIDO2 relying party (ADR-0013). The RP id is the effective domain and the
# origin must match the browser's — dev runs over HTTPS on :4001 (WebAuthn needs a secure
# context). Note the app key is literally `:wax_`.
config :wax_,
  origin: "https://localhost:4001",
  rp_id: "localhost"
